### ISSUE TITLE
prometheus operator in 💔 Degraded state

### ISSUE THREAD

**Issue by jessebot** [small-hack/argocd-apps#391]
Seeing this in the degraded prometheus argocd app:
<img width="1084" alt="screenshot of the Argo CD web portal with the the prometheus app of app's prometheus helm chart app in tree view. it shows the main app of apps in a degraded state, but only one resource, the prometheus operator in a degraded state. all other parts of the app of apps are healthy. further detail: there's a cute little squid riding a docker whale in the top left corner" src="https://github.com/small-hack/argocd-apps/assets/2389292/ba2ac649-24ce-4d71-bde4-dec74636ca67">

prometheus operator events show:
```
shard 0: statefulset prometheus/prometheus-prometheus-prometheus not found
```

for this resource:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
  creationTimestamp: '2023-12-01T10:04:29Z'
  generation: 1
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus-stack-helm-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 54.2.2
    argocd.argoproj.io/instance: prometheus-stack-helm-chart
    chart: kube-prometheus-stack-54.2.2
    heritage: Helm
    release: prometheus-stack-helm-chart
  name: prometheus-prometheus
  namespace: prometheus
```

This happened even when I tore down and rebuilt the cluster after https://github.com/small-hack/argocd-apps/pull/221 was merged. 🤔 @cloudymax curious for your input as I haven't had the time to look into it yet.
