### ISSUE TITLE
vouch-proxy external secrets SyncError

### ISSUE THREAD

**Issue by jessebot** [small-hack/argocd-apps#392]
After using smol-k8s-lab to deploy a k3s cluster with the latest changes for the main branch in this repo, I'm seeing that vouch is in a degraded state because it couldn't get its external secrets?

<img width="1213" alt="Screenshot of the Argo CD web interface showing the vouch-proxy app of apps for external secrets. The vouch-oauth-config app is shown in an error state" src="https://github.com/small-hack/argocd-apps/assets/2389292/92c620c3-812d-4242-9d6d-15044f848ffd">

When I click the Error, it shows:

> Failed sync attempt to 2ebd1634e1db01087536027588c73ab2da022389: one or more objects failed to apply, reason: ExternalSecret.external-secrets.io "vouch-oauth-config" is invalid: [spec.data[0].remoteRef.key: Required value, spec.data[1].remoteRef.key: Required value, spec.data[2].remoteRef.key: Required value, spec.data[3].remoteRef.key: Required value, spec.data[4].remoteRef.key: Required value, spec.data[5].remoteRef.key: Required value, spec.data[6].remoteRef.key: Required value, spec.data[7].remoteRef.key: Required value]

I think that's because the value for `vouchOauthConfigBitwardenID` wasn't rendered here:

```yaml
project: vouch
source:
  repoURL: 'https://github.com/small-hack/argocd-apps.git'
  path: vouch-proxy/external_secrets/
  targetRevision: main
  helm:
    values: |
      provider: bitwarden
      vouchOauthConfigBitwardenID: <no value>
      vouchConfigBitwardenID: 78fdagg-fda86-768dsf-7434-fdajlkfhjdkas
destination:
  server: 'https://kubernetes.default.svc'
  namespace: vouch
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - ApplyOutOfSyncOnly=true
```

... but... why? Will look into this as soon as possible, as it's important to have vouch up to secure prometheus.

Resyncing this vouch-external-secrets app doesn't fix it 🤔
